### ISSUE TITLE
How to define Repositories

### ISSUE THREAD

**Issue by DesireWithin** [ansible-semaphore/semaphore#1025]
I deploy semaphore in K8s, version is `v2.8.53`.
I try to run my first task. First I need define a workable ansible-playbook Repository.

Here are some screenshot: 
![repo1](https://user-images.githubusercontent.com/23254001/188430146-87c62733-1acd-42fc-810e-d155683767bb.png)
The qustion mark of `Access Key` filed told me I should use `None` type.(I don't know how to pass the gitlab verification)
I test `None` or `Personal Access Token` or `Login with Password`, All tasks failed:

![result1](https://user-images.githubusercontent.com/23254001/188429371-99b48141-c963-4ab7-9cb1-c5f709bec915.png)

Well, I found several similar Github issues like  #982 and #871

So, I chose to use local folder, but still, all tasks failed:
![result2](https://user-images.githubusercontent.com/23254001/188430383-86169fdc-1464-48e6-a813-795e41ee8c22.png)

I see many successful example of semaphore, but what should I do?
Please update the official document with more example.

**Comment by DesireWithin** [comment]
Today I test with `Login with Password` Https gitlab Repository, it's successful

**Comment by fiftin** [comment]
Hi @DesireWithin 

What do you think about Semaphore? What features is missing? )

**Comment by jhaesselbacher** [comment]
Web forms to enter variables like those of awx, with comboboxes, listboxes.... Before execution of the playbook? :)

**Comment by huangjian80s** [comment]
I looked at the previous issues and found that the docker version is faulty. If you use Package manager install, you can use file://

At the same time, I also tried the http:// method of self-built gogs, but found that it still does not work, SSH :// is too difficult for me to understand

**Comment by fiftin** [comment]
We have working demo. There are repo examples: https://demo.ansible-semaphore.com/project/1/repositories

**Comment by fiftin** [comment]
By the @DesireWithin issue, it is authentication problem.

`None` should be used for `https://` protocol without authentication.

I tested `Personal Access Token` it is works to me. I will try to reproduce the issue again.

**Comment by fiftin** [comment]
Hi @DesireWithin , 
I don't remember how I missed this but PAT working as login/password, just password is your PAT. Use  `Login with password` instead of `Personal access token`.

**Comment by fiftin** [comment]
How to fix: https://docs.ansible-semaphore.com/administration-guide/troubleshooting#fatal-bad-numeric-config-value-0-for-git_terminal_prompt-invalid-unit

**Comment by erioshi** [comment]
After your comments above I took another look at the situation.  The problem is specifically the HTTPS connection attempt.  When I set up my test container, I set it up without an HTTPS reverse proxy (just for testing).  To successfully connect to the container an HTTP connection is be required.

When I have time I'll put a reverse proxy in place and see if that resolves the issue.  While it is a best practice, I'm not sure that need for HTTPS connections is specifically called out in the wiki.

**Comment by gitwittidbit** [comment]
I am experiencing the same problem: using an internal http connection to my gitea instance, resulting in "invalid unit"

**Comment by gitwittidbit** [comment]
Is this setup (local http connection) supported? If not, I need to figure out how to proceed...

**Comment by bkraul** [comment]
For those still having issues with this, the solution for me was to specify a user with the "Login with Password" option. Previously the PAT approach would not need a password. Supposedly, with Login with Password, you just don't enter a user and the password becomes the PAT, but this is not the way it is working. The `GIT_TERMINAL_PROMPT` happens because somehow it is expecting a user name anyway (maybe the implementation does not follow what PAT used to do).

In any case, the easy fix is to enter a user name. I entered the user `git`,  and it worked flawlestly. I tested this from the command line to make sure it would work, basically constructing a URL like so:

```
git clone https://git:github_PersonalAccessToken@github.com/org/repo.git
```

And since this worked, I was confident it would work with semaphore.

**Comment by Hi-Res-Cam** [comment]
Thanks @bkraul 
Update to the latest semaphore version also broke my GitHub setup... Tried everything, in the end just setting a login/password and using **git** as a placeholder and pat in password field solved the issue.
Not sure why pat has been removed from the list and the documentation is not updated.
