### ISSUE TITLE
Cron at UTC time instead of local time

### ISSUE THREAD

**Issue by bverkron** [ansible-semaphore/semaphore#1042]
I have a cron for a task setup as follows (should be 1am local time) and it's running at 6pm local time, which seems to indicate it's running at 1am UTC

<img width="952" alt="image" src="https://user-images.githubusercontent.com/19174503/194193938-2d5d3d83-b77f-4423-86a7-c322ab347d44.png">

![image](https://user-images.githubusercontent.com/19174503/194194115-8ccc72ba-ed09-4271-83ae-0eb2660e6a0c.png)

![image](https://user-images.githubusercontent.com/19174503/194194178-aa22fb06-40af-423b-a335-e66fb1c1979c.png)

Being that the UI is in my local time I would expect the cron to match that (or vice versa to indicate everything is in UTC).

Is there a setting behind the scenes for the time zone that I can set? I don't see anything in the doc or UI.

**Comment by bverkron** [comment]
Possibly related to https://github.com/ansible-semaphore/semaphore/issues/974 ? Not sure if it's the same root cause (looks like DB timezone maybe?) or if it's something else.

**Comment by bverkron** [comment]
I would consider this a really low priority issue (not even sure if it's considered a "bug" or not) being that once you know this you can just account for it in the cron schedules by bumping them by the offset.

**Comment by gromavic** [comment]
Have you found reasons/solution?

**Comment by n1nj4888** [comment]
Is there any progress on this? The issue seems to be that the container timezone is always set to UTC. Other images usually allow the timezone to be set in a container using something like the TZ environment variable or mapping /etc/timezone or /etc/localtime from the host to the container - Both these methods don’t currently work and the container remains in UTC. 

Also - There’s currently no date/time or information in the UI that cron scheduled tasks will run against UTC. The user may expect that the task runs in their local timezone and so configures accordingly. This may cause further issues if the task then actually runs at later unexpected times.

**Comment by rmtsrc** [comment]
I recently ran into the same issue when using Ansible Semaphore in a Docker container.

I was able to fix it by sharing my host machines timezone settings via a volume and then restarting.

```yaml
services:
  semaphore:
    image: semaphoreui/semaphore
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
# ...
```

**Comment by xpliz** [comment]
> I recently ran into the same issue when using Ansible Semaphore in a Docker container.
> 
> I was able to fix it by sharing my host machines timezone settings via a volume and then restarting.
> 
> ```yaml
> services:
>   semaphore:
>     image: semaphoreui/semaphore
>     volumes:
>       - /etc/timezone:/etc/timezone:ro
>       - /etc/localtime:/etc/localtime:ro
> # ...
> ```

Sadly passing TZ mounts or env var doesn't change container timezone.

**Comment by Jojonintendo** [comment]
Just leaving some info here that worked for me.

I had to actually export /etc/localtime in **both** containers, semaphore and the DB.
This way, cron actually respects my timezone.

**Comment by linsomniac** [comment]
> I would consider this a really low priority issue (not even sure if it's considered a "bug" or not) being that once you know this you can just account for it in the cron schedules by bumping them by the offset.

I'll make a case for it being literally a bug.  User puts in a cron entry and it runs 7 hours early, that's unexpected.  UI doesn't say "Cron (in UTC)" so it's reasonable for the user to expect it to be in local time.  Having the user calculate the time in UTC is a workaround, but is bad UX.  Having the user have to go dig through Github Issues to find the fix is also bad UX.  Especially when "how to set TZ in docker container" google searches point you towards setting the TZ environment variable, and at that point all other commands on the system seem to show a local timezone.

Some possible fixes:

- Expose /etc/localtime and /etc/timezone into docker containers in docker compose file.
-  Have the UI say "Cron (in UTC)".

**Comment by cbrookins** [comment]
Pull request: https://github.com/ansible-semaphore/semaphore/pull/1730

**Comment by tboerger** [comment]
With the merged PR you should be able to provide the TZ environment variable to set the right timezone.

**Comment by linsomniac** [comment]
We just did an update and can confirm that it seems to be using the correct timezone.  Thanks!
