### ISSUE TITLE
Prompt for vault password

### ISSUE THREAD

**Issue by asmartin** [ansible-semaphore/semaphore#113]
Would it be possible to add a checkbox to playbook templates that will prompt the user for a vault file password before executing (used with `--ask-vault`)? This allow for users to manage their own vault file passwords without needing the administrator to keep plaintext copies of the vault file passwords on the semaphore server (used with `--vault-password-file`)

**Comment by matejkramny** [comment]
Sure, I agree, however vaults are a kind of a ball-ache because you need to edit them and put them into git

If the database entry (environment) was encrypted using a password only the user knows, as is the case with ansible vault (and `--ask-vault`), only that it gets decrypted whilst running, it serves the same purpose but with benefits.

I would rather execute something of that sort because it helps the user. On the other hand, it has the drawbacks such as being dependent on semaphore to run things.

What do you think?

**Comment by asmartin** [comment]
> If the database entry (environment) was encrypted using a password only the user knows, as is the case with ansible vault (and --ask-vault), only that it gets decrypted whilst running, it serves the same purpose but with benefits.

Do you mean storing an entry in the semaphore database that contains the vault password, but encrypted, and then passing it like `--ask-vault <decrypted-entry-from-semaphore-db>` when running the playbook?

**Comment by matejkramny** [comment]
Hmm no.. I propose that the environment JSON, per template be encrypted by a user-entered password (which isn't stored).

The environment sits in semaphore's database encrypted, but password is not saved. This is safe to an extent where the key isn't passed to semaphore and the environment doesn't sit on disk decoded whilst the task is running.
Now thinking about it, it could use the underlying technology (ansible vault) and the password would be passed to ansible.

**Comment by matejkramny** [comment]
Ok so final idea:

- Environment is encrypted by ansible-vault but in semaphore's database as `environment` of a template
- User is prompted for the decrypt password and that password is passed to ansible when running. This is beneficial because it won't be decrypted on disk at any time (as far as semaphore is concerned)
- This is better than having an ansible vault file in the git repo because it is easier for the user to manage (not having to decode, encode and commit files..)

**Comment by asmartin** [comment]
That idea is good for semaphore, but at least with my use case I need to be able to use the vault files with ansible outside of semaphore too, so a solution that is semaphore-dependent won't work for me. 

In order to be compatible with playbooks that are used in other environments, probably the best thing is to allow ansible to handle the vault files

**Comment by matejkramny** [comment]
Hmm agree. Either both should coexist or an option to pass passwords from the UI should be possible

**Comment by asmartin** [comment]
Sounds good!

**Comment by bshifflett** [comment]
Has there been any news on this enhancement or a workaround? I just installed Semaphore and really could use this for my environment.

**Comment by matejkramny** [comment]
There is a lot of work needed to get this working correctly @bshifflett.

See [roadmap](https://github.com/ansible-semaphore/semaphore/issues/325) for progress

**Comment by bshifflett** [comment]
I just got it to work by adding the extra variables to add in the command
line when running task ["--vault-pass","/path/to/.passfile"] and this
worked great.

**Comment by matejkramny** [comment]
Good! This ticket is about something more involved though.

The UI should ask you for variables/vault password as it does in the command line

**Comment by fiftin** [comment]
![image](https://user-images.githubusercontent.com/914224/133695053-41983d96-518a-449e-bd87-80e628c8733e.png)

Not prompt but use stored password can be used. Available in v2.7.20
