### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by hhenkel** [ansible-semaphore/semaphore#118]
From what I've seen so far users are stored in the database. It would be nice to have LDAP support, so that one could use existing groups to match "roles" and people could use their central managed password.

**Comment by rguiliani** [comment]
+1

**Comment by gasperzupancic** [comment]
that would be awesome!
+1

**Comment by matejkramny** [comment]
Please use github's reactions for +1's. Thanks!

This will be done when everything else is out of the way. There are currently more pressing things like an unfinished UI and dynamic inventories!

**Comment by Gianlu** [comment]
+1

**Comment by matejkramny** [comment]
Ok guys, in order to build this i need to know some detail.

Can you provide a use case?
is google apps (for business) an LDAP provider that you would use?
How would google apps permissions apply inside semaphore?

**Comment by Gianlu** [comment]
Hi,
I agree with @hhenkel. My use case is to authenticate users via active directory and it is (more or less) an ldap server. I need to authenticate users and map roles to users' groups for authorization.
@hhenkel proposed a good auhorization pattern.

**Comment by KarenTovmasian** [comment]
and plans for implementation of this? we need to auth users from AD or from Google (both works for us)

**Comment by gcavalcante8808** [comment]
@hhenkel @matejkramny Based on what hhenekl said, Initially I thought something like this for the Backend:

![auth](https://cloud.githubusercontent.com/assets/640897/20315074/a251d1ae-ab43-11e6-84ec-54716badd66d.png)

With in this in mind, we can think about the following behavior:

 * The Entity table have the information about data connection options and name;
 * An default 'Internal' entity will be included by default(fixtures);
 * An User have an Entity (only one) which can can be 'Internal', an 'LDAP User', or something else (maybe HTTP auth in the future?);
 * The Permission table have permission names: maybe something bound to our api calls, like "task_template_run", "task_template_update", "task_template_create" would be nice;
 * The roles_permissions tables maps an Role to a number of permissions;
 * The Role table have the role name;
 * The project_user_roles is a m2m that maps user->role-> project, so our user can have different roles in different projects;

To start, if have thinking about roles maybe we should implement an RBAC model ... but we are using angular to provide our frontend ... In this point I really don't have a clue (maybe a check within a service?) about how path we should go ... In the github we have https://github.com/mikespook/gorbac project for the server side ...

To finish the job we need an Authorization Management interface to manage Entities, Roles, Permissions.

What you think?

**Comment by gcavalcante8808** [comment]
I think that we should start with simplest approach: implement LDAP authentication with the authnz_entity table and integrate it with the GIN framework.

The following lib looks like to be the best implementation for now:

https://github.com/mavricknz/ldap

**Comment by mcassaniti** [comment]
I'm seeing two issues rolled together here. I too am in an AD environment, and I'm after a multi-tenant solution. You need three parts to solve the multi-tenant side:

1. User to authentication type mapping (the entity and entity_type tables)
1. RBAC
1. Groups or Organizations

I would suggest splitting RBAC into a separate issue since its implementation is independent of AD authentication. The other part that is missing from your RBAC model is limiting not only what actions can be performed, but what objects or group of objects they can be performed on. This is where the concept of an organization, or a mapping to a group is important.

To elaborate, if I can assign either an organization or a group to an inventory, then that group or organization can be used to limit which users can access that inventory. This is orthogonal to **what** a user can do with that inventory. Organizations are a 1:1 mapping to the object (in this case an inventory item), whereas groups are generally many to many.

**Comment by strangeman** [comment]
Hi, guys. I plan to implement a simple LDAP auth here, like "If this LDAP user have right password and belongs to right LDAP subtree - add it to the users table and authorize him". After, if it will be work good - we can do more complex things, like inventory/project/etc limitations.

**Comment by strangeman** [comment]
Added simple LDAP auth as described in my previous comment.

**Comment by Echobob** [comment]
Closed by #310

**Comment by matejkramny** [comment]
Now that LDAP is integrated (& soon the security issue fixed), I have some questions for you guys since I don't use LDAP systems.

Should the users be created in semaphore if they don't exist in the semaphore database but have been authenticated using LDAP?

Soon we'll have a better permissions system (starting with @strangeman's PR). Does LDAP have a permission system that semaphore can utilise?

We could also poll for users from the LDAP system and do something with that.

**Comment by pasikarkkainen** [comment]
@matejkramny : Can you please link the permissions PR you mentioned? 

Usually one uses LDAP groups, and map them to roles.. is that what you need, or something else?

**Comment by matejkramny** [comment]
Not a PR, an issue. I got that wrong. It's #344.

Possibly. My understanding of this: If one user was in the "admins" LDAP
group and it was configured to map to the "admin" permission in semaphore,
upon logging in for the first time (effectively signing up to semaphore)
the user would be automatically "admin".

On 20 May 2017 19:08, "pasikarkkainen" <notifications@github.com> wrote:

@matejkramny <https://github.com/matejkramny> : Can you please link the
permissions PR you mentioned?

Usually one uses LDAP groups, and map them to roles.. is that what you
need, or something else?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ansible-semaphore/semaphore/issues/118#issuecomment-302886096>,
or mute the thread

**Comment by hhenkel** [comment]
@matejkramny I'll try to describe quickly what I've seen in other applications:

Other application normaly allow you to specify an ldap search string, which can consist of multiple "conditions" or "rules" (and / or combinations).

For the mapping part it is a s I initialy wrote and comes down to what @pasikarkkainen wrote:

A user is normally a member of 1 to n groups
A group normally consists of 1 to n members

An application normally works with the concept of roles like "admin" or "user". When using an LDAP backend you normally try to map groups to roles to make administration easier but one could also map specific users to a role.

>  Possibly. My understanding of this: If one user was in the "admins" LDAP group and it was configured  to map to the "admin" permission in semaphore, upon logging in for the first time (effectively signing up to semaphore) the user would be automatically "admin".

You should always evaluated if the user still is in the admin LDAP group and not depend on what has been set in the database, as the permissions could have been revoked in the LDAP.

**Comment by strangeman** [comment]
Currently, Semaphore haven't 'admin' users (see https://github.com/ansible-semaphore/semaphore/issues/318)

Also, we should be able to map LDAP groups to the different Semaphore projects.

**Comment by hsluoyz** [comment]
Hi, I'm the author of Casbin. [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC. See details here: https://github.com/casbin/casbin

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database (MySQL and Cassandra).

It also supports superuser like admin. And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Please consider using it, I can provide help if you need. Thanks!

**Comment by bioinfornatics** [comment]
it is a nice to have +1
