### ISSUE TITLE
Should have support for providing environment variables

### ISSUE THREAD

**Issue by rguiliani** [ansible-semaphore/semaphore#121]
I see a TODO in the code regarding environments. This would be good since I can use that to provide an env var for ansible vault password file.

**Comment by matejkramny** [comment]
You can provide environment through the interface.

The TODO in the code might be a bit out of date since environment is specified here: https://github.com/ansible-semaphore/semaphore/blob/f16b3a57e8412c95962f8b1f9a9f13d5398d7ce0/api/tasks/runner.go#L26

It was planned to write it to file but a CLI option was available.
