### ISSUE TITLE
Why so hard to add screenshots?

### ISSUE THREAD

**Issue by babatundebusari** [ansible-semaphore/semaphore#133]
I would think it is obvious to know that a GUI project will have screenshots so people know how the GUI looks like. So far i can see some **very tiny** images, not sure if that was on purpose or something, but no way to actually see how this thing looks like.

It is unfortunate that that is indeed not obvious. 
No demo page and no screenshots to show how the GUI looks like

**Comment by matejkramny** [comment]
see https://raw.githubusercontent.com/ansible-semaphore/semaphore/master/public/img/screenshot.png

**Comment by babatundebusari** [comment]
Is that the only one?

Will be nice to add this to readme section under like screenshots

**Comment by matejkramny** [comment]
There is a tutorial being built here: https://github.com/edib/ansible-semaphore

There's the tutorial and we might also have a 'demo mode' inside the product that guides you through using the interface.

Its WIP since some of the UI is still being improved/changed by #94 and will be done after the most important things like dynamic inventory

**Comment by timruffles** [comment]
Why not pop a screenshot on the frontpage of the github repo? Seems counter-productive to hide all the good work you've done!
