### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by UNiXMIT** [ansible-semaphore/semaphore#1627]
I've configured Slack in Semaphore:
```
"slack_alert": true,
"slack_url": "https://slackWebhook/abcd",
```

I've enabled alerts everywhere I could find a checkbox in the UI:
"Allow alerts for this project" set on the project.
"Send alerts" is set for the user. 
The task does NOT have to be "Suppress success alerts" checked. 

But still no notification sent when a task succeeds.

I am running version 2.9.37 in a container on Linux (Rocky 9.2). 
A curl command to the same webhook from within the container is successful. 

Any ideas what could be wrong or any diagnostics I can check to investigate this further?
Thanks

**Comment by Alex-Giaquinto** [comment]
@UNiXMIT I have had the same issue with the last two or three releases, don't think it has ever worked.

**Comment by fiftin** [comment]
Hi @UNiXMIT 

will check soon, thank you!

**Comment by aaronnad** [comment]
@Alex-Giaquinto I've had slack notifications working on 2.9.4.

```
Can't send slack alert! Response code: 400
```
On 2.9.37 running on Rcky Linux VM, i am getting the above now

**Comment by aaronnad** [comment]
```
Can't send slack alert! Response code: 400
```
On 2.9.37 running on Rcky Linux VM, i am getting the above now - this was working on 2.9.4

**Comment by John-Limb** [comment]
I've noticed in my playbooks I am now getting
Can't send slack alert! Error: Post "": unsupported protocol scheme ""

My config looks like

slack-alert         true
slack-url           https://hooks.slack.com/services/xxxyyy/xxxyyy/xxxyyysssyyy

**Comment by thibaultserti** [comment]
For me it's working but only for Task ending in success
For failure, it seems the problem comes from the color "bad" which doesn't exist and cause a 400

Color defined here: https://github.com/ansible-semaphore/semaphore/blob/570a9d323ab02834041bddaf91fa651b5a9f1c69/services/tasks/alert.go#L205
Slack documentation: https://api.slack.com/reference/messaging/attachments#fields

The color to use is "danger"

I am testing this with Discord Slack compatibility tough
