### ISSUE TITLE
Using ansible on AWS instance

### ISSUE THREAD

**Issue by adnaan-s** [ansible-semaphore/semaphore#1692]
Hi, there I'm practicing to use Ansible on my AWS Ubuntu instance, I have successfully installed Ansible and created hosts.ini and ansible.yml playbook. When trying to run ansible. It gives me this error.

fatal: [18.60.85.107]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@18.60.85.107: Permission denied (publickey).", "unreachable": true}
fatal: [18.61.5.74]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.61.5.74' (ECDSA) to the list of known hosts.\r\nroot@18.61.5.74: Permission denied (publickey).", "unreachable": true}

I'm trying to install install Nginx server on my BOTH DIFFERENT Ubuntu INSTANCES. I don't know how to add private key and wher??? Someones help would be appreciated!! Thanks.

**Comment by andreas-marschke** [comment]
Your problem is with Ansible and not with Semaphore. We're not a general Ansible support forum. I suggest you to learn about SSH, how authentication and keys work at least at a rudimentary level and possibly approach an Ansible support forum if you've not been successful in troubleshooting it by yourself.

As this ticket is not about Semaphore, I urge you to close it.
