### ISSUE TITLE
[ARM] Illegal instruction when trying to install

### ISSUE THREAD

**Issue by stylersnico** [ansible-semaphore/semaphore#174]
Hi,

I have just owned a raspberry Pi 0 and I want to install Semaphore on it but I can't.

The following commands: 

``` bash
curl -L https://github.com/ansible-semaphore/semaphore/releases/download/v2.0.4/semaphore_linux_arm > /usr/bin/semaphore
chmod +x /usr/bin/semaphore
semaphore -setup
```

Results into:

``` bash
Illegal instruction
```

Any idea?

Hardware:
- Raspberry Pi 0
- Up to date Raspbian 8
- Ansible 2.x from backports
- MariaDB

Thanks

**Comment by twhiston** [comment]
I think this is due to gox being used to do the cross compile and needing to be more specific about GOARM https://github.com/mitchellh/gox/issues/67
You should try compiling it yourself on the pi, or cross compile from another computer. It's on the cards to change gox for goreleaser anyway so hope to get this sorted in a future release
