### ISSUE TITLE
What's the 'Environment' and how to use it?

### ISSUE THREAD

**Issue by GoodHaHa** [ansible-semaphore/semaphore#222]
What's the 'Environment' and how to use it? Thinks a lot.

**Comment by matejkramny** [comment]
It's used to declare environment variables for the playbook, similar to what you would do on the command line

**Comment by mikequentel** [comment]
@matejkramny please, would you show an example? I am trying to set the PATH to include the location of the maven binary, like this: `{"PATH":"$PATH:/opt/apache-maven-3.1.1/bin"}`

**Comment by matejkramny** [comment]
I think it's in the following format, without extra environment key:

```
{
    "PATH": "{{ansible_env.PATH}}:/opt/apache-maven-3.1.1/bin"
}
```

**Comment by mikequentel** [comment]
Hi @matejkramny many thanks for the tip...the values are not getting exported to underlying shell scripts, but the syntax correctly parses. Now I am trying this: `{"PATH": "{{ansible_env.PATH}}:/opt/apache-maven-3.1.1/bin","MAVEN_HOME": "/opt/apache-maven-3.1.1/bin"}` -- Semaphore appears to successfully consume that, but shell scripts called from the playbook do not recognise the `MAVEN_HOME`, for example. But that is probably due to the shell scripts being launched in another process. I shall keep hacking at this.

Many thanks for your help and advice. Semaphore is a great tool.

**Comment by matejkramny** [comment]
I'm happy it works for you. Let us know if you need anything
