### ISSUE TITLE
Seeing 'Bugsnag: Error: spawn ENOENT'

### ISSUE THREAD

**Issue by vsayer** [ansible-semaphore/semaphore#23]
At version e8ce2a7, seeing the following error after starting semaphore as 'nodemon bin/semaphore'

app.js:110 Semaphore listening on port 50000
../node_modules/bugsnag/lib/logger.js:29 Bugsnag: Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

This is probably not an issue, but need help debugging this. I don't know where to start.

**Comment by vsayer** [comment]
Oh and also, this is against Node v0.10.36 on CentOS 6.6

**Comment by matejkramny** [comment]
Have you got ansible installed?

**Comment by vsayer** [comment]
actually resolved it...turns out git wasn't installed on system and this error was due to that...this link helped a lot to resolve: http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

To fully resolve this, I'd still recommend adding a 'Requirements' section to README.md that includes git, mongodb, redis, etc, but it's up to you :)

Cheers!

**Comment by matejkramny** [comment]
Ok
We have docker images though which remove the need of installing stuff but yes
there should be instructions for manual install..

On Tue, May 26, 2015 at 8:23 am, Vivek Ayer <notifications@github.com> wrote:
actually resolved it...turns out git wasn't installed on system and this error
was due to that...this link helped a lot to resolve: 
http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
[http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js]

To fully resolve this, I'd still recommend adding a 'Requirements' section to
README.md that includes git, mongodb, redis, etc, but it's up to you :)

Cheers!

—
Reply to this email directly or view it on GitHub
[https://github.com/ansible-semaphore/semaphore/issues/23#issuecomment-105424081] .[https://github.com/notifications/beacon/AAwrqNJf0DNZ_DWqfU2OTgLRn3wtyUx3ks5oNBbcgaJpZM4EUa__.gif]
