### ISSUE TITLE
Dynamic Inventories grayed out

### ISSUE THREAD

**Issue by alledm** [ansible-semaphore/semaphore#242]
Hello,

I have just installed semaphore 2.1.0 on a local/test setup.

I have configured a gcloud key on the keystore, but I don't seem to be able to configure a dynamic inventory.

When I go to the inventory section of the project, all dynamic inventories are grayed out.
Am I missing something?

**Comment by alledm** [comment]
This is confirmed on 2.0.4 as well

**Comment by matejkramny** [comment]
Hi Alessandro, dynamic inventories are not yet supported.

There is a ticket for this however it was missed for 2.1

Matej

On 23 Dec 2016 02:54, "Alessandro De Maria" <notifications@github.com>
wrote:

This is confirmed on 2.0.4 as well

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ansible-semaphore/semaphore/issues/242#issuecomment-268854129>,
or mute the thread

**Comment by alledm** [comment]
Pity. Thanks!

**Comment by twhiston** [comment]
dup of #47
