### ISSUE TITLE
Allow copying a task templates

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#259]
In our infrastructure, we use one big playbook which can install/update the entire infrastructure. Separate parts of this playbook we launch with various tags. 
So, in Semaphore paradigm we using almost equal task templates (the same Playbook Name, SSH Key, Inventory, Playbook Repository and Environment, but different Extra CLI Arguments (["--tags=app1"], ["--tags=app2"], ["--tags=app3"])). For almost equal templates Clone/Copy button will save many time.

**Comment by laeshiny** [comment]
I have two ideas like below

- Idea 1
1. Click the copy button by the run button
2. Semaphore creates the same template then show new one on the template list
3. Edit this

- Idea 2
1. Click the copy button by the run button
2. Semaphore opens the adding modal with the filled same content (Playbook Name, SSH Key, Inventory, Playbook Repository and Environment) 
3. Edit this

I think the second one is better than the another one because after user copy the template, he needs to edit that.

**Comment by strangeman** [comment]
Yeah, the second variant is much better!

**Comment by laeshiny** [comment]
I'm going to try it

**Comment by strangeman** [comment]
https://github.com/ansible-semaphore/semaphore/pull/297
