### ISSUE TITLE
Resources loaded from realtive root URL

### ISSUE THREAD

**Issue by JWThewes** [ansible-semaphore/semaphore#350]
We've set up Semaphore. It's working fine so far.
Now we wanted to integrate it behind our reverse proxy.

So Semaphore should be accesible under https://<OUR_DOMAIN>/admin/semaphore
When accessing the URL we get the Semaphore page but CSS and JS is missing. This is because all the resources are loaded via /public.
It should be public without the leading /

This would enable Semaphore to be integrated into every envrionment. I don't see any reason why the resources should be loaded absolute.

**Comment by matejkramny** [comment]
Indeed they should be relative, however this project uses html5 pushstate and virtual paths, loading "/project/2" which is actually `/index.html` and JS serving up the relevant page.

This can be fixed with `<base href="/relative/path/"/>` in the head but this would need to be configurable.

Another alternative is using a subdomain

**Comment by verybigbadboy** [comment]
I have same issue, how can I change base path?
