### ISSUE TITLE
Add paginator (or lazy loading) for Events and Project activity lists

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#367]
Currently, we have about 4000 entries in Event table and the main page loading about 5 seconds or so. Can we load only the last 100 entries and create paginator?

**Comment by matejkramny** [comment]
We could just limit the number of events returned from the api

**Comment by ecornely** [comment]
I recently discovered spring-boot way of dealing with pagination and would suggest to implement an equivalent : http://ankushs92.github.io/tutorial/2016/05/03/pagination-with-spring-boot.html

Instead of returning a list of object you always return a page of object which encapsulate the liste plus meta-information about how many pages are available, the current page and so on...

Determine a certain default page size and let change the page number/page size/sort by query parameters

It should change a lot the javascript (just need to unwrap the list) and when needed add the next and previous buttons.

**Comment by twhiston** [comment]
closing due to #402 , if anyone wants to take this further please open a new issue
