### ISSUE TITLE
ansible runs as semaphore user

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#424]
is it possible to have the user logged into semaphore be the user in which ansible tries to log into the inventory hosts?

it would be interesting to expose users to plays but only have them be able to run them against server's their user has access 

I guess to do this each user in semaphore would need a key assigned to them to?

**Comment by twhiston** [comment]
I think this would mean that the key handling would have to be very different as they would need to be tied to users, possibly shared between projects etc.... I think it adds a lot of complexity. As 2.5.0 will have a non admin role in it for now you could perhaps just manage this via different projects for different users and decide what access they have.
@twotwenty If you are willing to make a PR for this feature I would be really happy to review, but otherwise i'm not sure it will get in any time soon. Please drop a comment if you fancy giving it a try

**Comment by radarsugarcrm** [comment]
Hi,
seems that I currently facing the same issue.
Even if I use "--user=username" under "extra CLI Arguments" for the template.
Playbook will not be executed wit above username.

If I use the same "extra CLI Arguments" on command line it is working like expected.
Or did I miss something?
running semaphore_2.7.22_linux_amd64.deb

**Comment by fiftin** [comment]
You can add following field to your environment:
```
{
  "ansible_user": "username"
}
```

or you can create Access Key with type `Login with password` and use it in Inventory.

**Comment by radarsugarcrm** [comment]
thx a lot :+1: 
works like charm
