### ISSUE TITLE
Love Semaphore

### ISSUE THREAD

**Issue by twotwenty** [ansible-semaphore/semaphore#437]
I am currently deploying semaphore in a production environment but I noticed awx was released as OSS 
will this effect semaphore ? is the project going to continue ?

**Comment by matejkramny** [comment]
This project isn't here to compete, but to offer an interface to ansible which was missing before. Now that awx is out it's for the better for the ansible community.

Semaphore will continue to exist, even though it's development has slowed lately. That's not due to the release of awx but to the time available to spend on this project.

**Comment by twotwenty** [comment]
the interface was missing before, I have not yet tried awx.  I appreciate semaphore for its elegant interface. 

Thanks Matejkramny

if you ever visit Kelowna Canada be sure to say hi the beer is on me.

**Comment by matejkramny** [comment]
Thank you, likewise if you visit Oxford (UK)
