### ISSUE TITLE
Semaphore UI can upgrade Angular 2.0+?

### ISSUE THREAD

**Issue by ssrshz** [ansible-semaphore/semaphore#444]
Lot's of angularjs projects do it.
Whether Semaphore has a plan？

**Comment by gcavalcante8808** [comment]
I think this should be included in the ROADMAP. 

Still, the ansible semaphore is a simple and cool solution to manage and apply ansible playbooks; The opensource Tower(AWX) is still too big, we should help and maintain this project alive.

**Comment by twhiston** [comment]
It would be fantastic if some willing FE developers would take on this task and work out how to bring it to production. Any volunteers?

**Comment by strangeman** [comment]
As I see it was fixed with https://github.com/ansible-semaphore/semaphore/pull/479

**Comment by twhiston** [comment]
Unfortunately not as #479 is still angular 1. Moving to Angular 2 is more of a total rewrite situation, and actually instead of directly going that way I think we should broaden the task out and talk about if we should stick with angular, go to vue, or react etc...... That JS FE world moves fast, so we should take the opportunity to assess what will be best going forward.

**Comment by fiftin** [comment]
Migrated to Vue.js
