### ISSUE TITLE
Semaphore don't delete the inventory files

### ISSUE THREAD

**Issue by MrTwIXx** [ansible-semaphore/semaphore#448]
Hey there,

AFter some executions from playbooks with semaphore, I saw a lot inventory files in the semaphore directory.
Is there a way that Semaphore delete them automaticly after finishing the playbook?

Thanks for the answer

**Comment by twhiston** [comment]
I can see two solutions to this that don't involve a lot of changes:

1 - move the inventory files to their own sub directory, allowing you to schedule a cronjob to delete them as needed.
2 - change the way that inventory files are named and use the project id instead of the task id to identify them, overwriting them each time.

Personally I prefer the 1st option as it allows you to keep an audit trail of inventory changes if needed

**Comment by strangeman** [comment]
Partly duplicate with https://github.com/ansible-semaphore/semaphore/issues/328

**Comment by strangeman** [comment]
Yeah, first option is better

**Comment by twhiston** [comment]
@strangeman what files that Semaphore writes should we consider ephemeral?

IMO everything in the `util.Config.TmpPath` could be considered that, except `semaphore_config.json` which gets placed there by `semaphore-startup.sh`. If we move this file we can just consider the whole directory as expendable and either write it to /tmp or schedule a cron job to delete it. That way we don't really need to introduce any logic around clearing up or not (global or task level, ui changes etc.... its a fair bit of work for a small feature imo) inside the application. What do you think?

**Comment by strangeman** [comment]
Looks good for me. This is an easy and effective solution.

**Comment by twhiston** [comment]
first part of this is merged (creating tmp dir if it does not exist #461)
