### ISSUE TITLE
Call for new maintainers

### ISSUE THREAD

**Issue by matejkramny** [ansible-semaphore/semaphore#451]
Hi all,

As a core maintainer of this project, I've not had enough time & energy to move this project further (for quite some time).
Rather than leaving this project at a stalemate, we thought it'd be best to hand it off to someone who can look after it.

If anyone is interested in taking up this role, please respond here or email us privately at hello@castawaylabs.com.

Regards,
Matej

**Comment by twhiston** [comment]
I'd be really interested in this. Happy to chat about it here or email or discord.

**Comment by strangeman** [comment]
I interested in this project. I'm not sure that I can intensively develop the project, but at least I can keep an eye on it.

**Comment by wmfairuz** [comment]
I'm interested to help as well. Mainly on the frontend (angularjs) side.

**Comment by twhiston** [comment]
@wmfairuz That would be awesome! FE is for sure an area I can't cover (if i end up as a maintainer :P)

**Comment by Xyon** [comment]
@strangeman I'm in the same boat, not sure I can hack on it intensely, but keen to help the project continue as well as it can.

**Comment by fiftin** [comment]
I'm interested to help too

**Comment by twhiston** [comment]
Hi @strangeman @wmfairuz @Xyon @fiftin , as you probably guessed I was made a maintainer on the project for the moment, so I just wanted to say hi to everyone that offered to help here. Its super cool to have you all on board and I hope we can start to get releases and fixes out faster, and continue to improve on the awesomeness that is Semaphore.

As you may have seen I started to tag issues with potential release versions, and put together a project for the [next release ](https://github.com/ansible-semaphore/semaphore/projects/2). This release should just deal with a few blocking bugs and things that people have already fixed and have PR's open for, I hope that this gets us to a good stable point where we can start to focus on improvements and new features. I will start to merge all the 'ready' tickets for 2.5.0 into develop next week and if you want to contribute currently I would ask you to kindly look at the issues in the project board that are still open or In Progress/In Review and help with getting them to ready. Also if a killer feature you need is missing and you have code already please open a PR so that we can review it and get it released ASAP.

If anyone wants to have an informal discussion about anything Semaphore related i'm generally always on the discord chat so come and find me there and lets talk! Once again thanks to you all for volunteering to help and I look forward to us all working together.
