### ISSUE TITLE
Bind semaphore on local interface in v2.5.0 does not work

### ISSUE THREAD

**Issue by Twim4** [ansible-semaphore/semaphore#538]
Hi

I am trying to bind semaphore to loopback interface like it was possible in previous v2.4.1 with config entry like:

<pre>
{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "xxxxx",
                "pass": "xxxxx",
                "name": "xxxxx"
        },
        "port": "127.0.0.1:3000",
...
</pre>

After semaphore upgrade from 2.4.1 to 2.5.0 the local interface binding is not working anymore:

<pre>
# semaphore -version
v2.5.0
</pre>
after service restart i'm  receiving following error message:

<pre>
Semaphore v2.5.0
Port :127.0.0.1:3000
MySQL semaphore@127.0.0.1:3306 semaphore
Tmp Path (projects home) /opt/semaphore
Checking DB migrations
time="2018-05-08T15:52:22+02:00" level=panic msg="listen tcp: address :127.0.0.1:3000: too many colons in address"
panic: (*logrus.Entry) (0x9eefc0,0xc42027e5a0)
</pre>

Maybe it would be a good idea to implement such parameter like "(bind_)ip": "0.0.0.0" or something similar.

Does somebody know some workaround for this issue to be able to bind it to local interface?

Thanks!

**Comment by twhiston** [comment]
Technically the fact you used to be able to put a full IP in there is an abuse of the field and we added validation for the port (because it should only be a port) to ensure it starts with `:` due to error reports where people expected that you could just put the number in the field.

So in your example it is prepending `:` to your string see `util/config.go` L208.
If we want to allow a full ip here we should introduce another config field for it. @strangeman thoughts?

**Comment by Twim4** [comment]
totally agree with explanation about the port config line.

But the thing is here, that i want to hide semaphore behind nginx reverse proxy, to not be able to connect to it from elsewhere except proxy. And with this config it is not possible.

**Comment by twhiston** [comment]
Your use case is totally valid and i'm happy to support it, but we will need to add a new field rather than revert the port field fix. 
As a temp workaround you can always compile it without that check as we only do it in one place (config.go L197), but in the long term we need a proper solution. It would actually be really simple as we only use the port in a few places. I would of course be very happy to accept a PR if you want to make one.
