### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by Fuckthesystem1** [ansible-semaphore/semaphore#565]
I have CentOS Linux release 7.3.1611 (Core) , semaphore v2.4.1

Trying to upgrade and see this:
current release is v2.4.1
panic: cannot find binary for your system

goroutine 1 [running]:
main.main()
        /Users/m/p/semaphore/cli/main.go:30 +0x62b

**Comment by strangeman** [comment]
Hello! Please, explain how you're trying to upgrade. Via `upgrade` button in the admin section?

**Comment by Fuckthesystem1** [comment]
Hello. Via Linux terminal by semaphore -upgrade

**Comment by Fuckthesystem1** [comment]
Hello. Via linux terminal - semaphore -upgrade.

**Comment by strangeman** [comment]
Did you rename semaphore binary? `-upgrade` flag trying to search binary with the name `semaphore_OS_ARCH`.

https://github.com/ansible-semaphore/semaphore/blob/develop/util/upgrade.go#L93
```go
func findAsset(release *github.RepositoryRelease) *github.ReleaseAsset {
	for _, asset := range release.Assets {
		if *asset.Name == fmt.Sprintf("semaphore_%s_%s", runtime.GOOS, runtime.GOARCH) {
			return &asset
		}
	}

	return nil
}
```

**Comment by Fuckthesystem1** [comment]
I didn't. What should I do to make it work?

**Comment by strangeman** [comment]
Can you provide a bit more information? How you installed Semaphore? How named a Semaphore binary?

**Comment by Fuckthesystem1** [comment]
I installed whith this instruction
https://github.com/ansible-semaphore/semaphore/wiki/Installation
Semaphore binary location: /usr/bin/semaphore
When I invoke semaphore it says:

Semaphore 2.4.1
Port :3000
MySQL root@127.0.0.1:3306 semaphore
Tmp Path (projects home) /tmp/semaphore

 Have you run semaphore -setup?
panic: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

goroutine 1 [running]:
main.main()
        /Users/m/p/semaphore/cli/main.go:43 +0x3af

But it works.

**Comment by strangeman** [comment]
Huh, looks like this instruction conflicts with programmed upgrade procedure. I'll take a look at it.

**Comment by Fuckthesystem1** [comment]
Hello! Any updates?

**Comment by fiftin** [comment]
@Fuckthesystem1 If it is actual to you, it is a bug. Problem is not in the instruction, I will fix it is the next release.

**Comment by fiftin** [comment]
I think this feature will be removed. Reason: I want to add separate user for Semaphore service with limited permissions. It is a bad idea to run Semaphore as root.

**Comment by cskutan** [comment]
Hi guys, I've tried to upgrade from semaphore (v2.5.1) to the latest stable version (v2.7.0).
I've downloaded the binary semaphore_2.7.0_linux_amd64.deb and executed the following:

`dpkg -i semaphore_2.7.0_linux_amd64.deb`
(Reading database ... 169789 files and directories currently installed.)
Preparing to unpack semaphore_2.7.0_linux_amd64.deb ...
Unpacking semaphore (2.7.0) over (2.5.1) ...
Setting up semaphore (2.7.0) ...

`semaphore -version`
v2.7.0

Neither through the webinterface upgrade button nor the linux cli am I able to perform a version upgrade because I am getting the "cannot find binary for your system" error as mentioned above.

I am fully aware that I could just easily reinstall semaphore with the latest version but it is essential to me that there is a reliable way of upgrading because I am considering using semaphore in our business.

I would really appreciate it if you could give me an update regarding this issue. Thank you!

Best Regards,
Christian

**Comment by fiftin** [comment]
Hi @cskutan,

You say about error "cannot find binary for your system", but how `semaphore -version` is work?

Need more details about issue. Thank you

**Comment by fiftin** [comment]
Option -upgrade removed.
We added snap https://snapcraft.io/semaphore and if you want this feature you should install semaphore via snap.
