### ISSUE TITLE
Handle roles and collections better

### ISSUE THREAD

**Issue by c-erb** [ansible-semaphore/semaphore#645]
Hi everyone, I would have a request for two things about the automated role and collection installation.

1. Use custom role and collection path
2. Option to disable --force for the ansible-galaxy installation.

For the first improvement, please see https://www.jeffgeerling.com/blog/2020/ansible-best-practices-using-project-local-collections-and-roles. It would be great if the environment variables collections_paths and role_paths wouldn't be just ignored.

The second improvement would be great as collections can be quite big and if you use a lot of roles you have a lot of traffic and waiting time when you run a task template (every time).

Thanks.

**Comment by TrayserCassa** [comment]
It would also be nice, to document a small example of an dependency like posix.synchronize for example. Currently I am struggling to get this working :/

**Comment by TrayserCassa** [comment]
@Gyilkos91 

I want to add your feature, because I think it is a small change. Point 1 is straight clear and easy to check. But Point 2 needs some advise where @fiftin wants to manage Project related things. Also Ansible is version handling very unlikely, see this:

https://github.com/ansible/ansible/issues/6466

So if you want to change the version, we need to make a --force update. Maybe we can add this to the play command as an checkbox, and control the behavior with the config. Maybe some nice ideas @fiftin ?

**Comment by fiftin** [comment]
@TrayserCassa, @Gyilkos91 I'm not sure by Point 2. `ansible-galaxy install` without `--force` ignores version changes in `requirements.yml`. Right? Should we check changes (for example by md5) and run `ansible-galaxy install --force` if it is changed?

I want Semaphore to be more automated. Checkbox is something manual.

**Comment by TrayserCassa** [comment]
@fiftin Ok I think this is nice to be more automated, but also more work to do :sweat_smile:  
Yes if you change the version in the requirements, then you get a warning:
```
Starting galaxy role install process
[WARNING]: - geerlingguy.java (1.10.0) is already installed - use --force to change version to
12.0.1
```
1. You want to md5 the requirement.yaml and if this changed after an git change you will use force.
2. check the current git head for changes in any requirements file (I think this is the nicest way, because I use this on a git hook to check if the version file hast changed on master and reject the push request, if the file has no changes) 
3. Maybe we can use `ansible-galaxy list` to list modules and parse the output and read the requirements to check if the version has changed. (First idear, I think not the beast one)

**Comment by fiftin** [comment]
@TrayserCassa at your discretion :)

**Comment by TrayserCassa** [comment]
@fiftin
Pr is open, I cant link it, so i will mark you here :)

**Comment by fiftin** [comment]
Done by @TrayserCassa, merged to `develop` branch https://github.com/ansible-semaphore/semaphore/pull/661
