### ISSUE TITLE
Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by Vladozoff** [ansible-semaphore/semaphore#675]
I run docker container ansiblesemaphore/semaphore.  When I run playbooks the following error is thrown
 UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.", "unreachanble":true}

**Comment by fiftin** [comment]
Add `host_key_checking = False` to Ansible config file.

**Comment by Vladozoff** [comment]
@fiftin , How can I access the config in a docker container? i start the container in the following way: sudo docker run --link mysql -e SEMAPHORE_DB_HOST=mysql -p 3000:3000 ansiblesemaphore/semaphore

**Comment by fiftin** [comment]
You can try to use Ansible environment variable `ANSIBLE_HOST_KEY_CHECKING`:

```
sudo docker run --link mysql -e ANSIBLE_HOST_KEY_CHECKING=False -e SEMAPHORE_DB_HOST=mysql -p 3000:3000 ansiblesemaphore/semaphore
```

**Comment by trubacca** [comment]
This behavior makes perfect sense in retrospect, but jeezy petes it took most of a morning to figure out what was going on here, specifically when using the docker image where the known hosts wasn't populated. 

This setting can also be applied using ansible.cfg, but my preference is to include it in the inventory as a host var, which might be a preferable solution when managing multiple environments with varying policies:
```yaml
sbc:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: captain
  ...

```
May I suggest adding that line (ANSIBLE_HOST_KEY_CHECKING=False) as an example within the "environment" field, or mentioning this in the docs? In fact, that seems like a simple contribution I can make myself if I had the OK to submit a PR.

**Comment by fiftin** [comment]
@trubacca Yes, thank you!

**Comment by dcolley** [comment]
if your inventory is in `ini` format, add this config:
```ini
[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
```

**Comment by philnewm** [comment]
Since I encountered this issue recently and was able to solve it for my limited setup, I will just quickly describe here what I found out about this.

For context:
- I'm using semaphore in a docker as well
- pulls the playbook from a GitHub repo
- setup is currently pretty small and simple since I'm still learning Ansible

my ansible.cfg - which is also used for local testing:
```
[defaults]
inventory = hosts
host_key_checking = False
ansible_python_interpreter = $HOME/.virtualenvs/python3.10.8/ansible_env/bin/python3.10
```

Since semaphore seems to overwrite the inventory and the interpreter path anyway, I thought I don't need to upload this file anymore.
But from what I found out, I was wrong: it uses the line: `host_key_checking = False`

You can also set this in the environment variable: `ANSIBLE_HOST_KEY_CHECKING=False` if you prefer that.

This is probably not a big deal at all, but I was confused by it a bit because I could not find any documentation on which values get overwritten by semaphore at which not. If you know where to find it, pls tell me.

**Comment by HerrSammyDE** [comment]
> Since I encountered this issue recently and was able to solve it for my limited setup, I will just quickly describe here what I found out about this.
> 
> For context:
> 
> * I'm using semaphore in a docker as well
> * pulls the playbook from a GitHub repo
> * setup is currently pretty small and simple since I'm still learning Ansible
> 
> my ansible.cfg - which is also used for local testing:
> 
> ```
> [defaults]
> inventory = hosts
> host_key_checking = False
> ansible_python_interpreter = $HOME/.virtualenvs/python3.10.8/ansible_env/bin/python3.10
> ```
> 
> Since semaphore seems to overwrite the inventory and the interpreter path anyway, I thought I don't need to upload this file anymore. But from what I found out, I was wrong: it uses the line: `host_key_checking = False`
> 
> You can also set this in the environment variable: `ANSIBLE_HOST_KEY_CHECKING=False` if you prefer that.
> 
> This is probably not a big deal at all, but I was confused by it a bit because I could not find any documentation on which values get overwritten by semaphore at which not. If you know where to find it, pls tell me.

I have exactly the same intention with the Github repo etc.. 

I have Ansible and Semaphore on a VM and have 

```
[defaults]
host_key_checking = False
```

in ansible.cfg, but it was ignored by Semaphore, so your tip with the environment variable worked very well

**Comment by LeonvanHeerden** [comment]
Since I am new to Semaphore, I was not able to quickly find a solution to this issue.  This issue did help find the working solution. 

1. Ideally, I would have liked to have the host checking on to ensure that servers are correct. But not know how to manage that through this interface yet...

2. I want with the Environment Variable. 
![image](https://github.com/ansible-semaphore/semaphore/assets/12222225/3c3fa6f7-a4b3-4f6b-bee2-f4d89277aa43)

3. I don't know where the ansible.cfg file is located on a docker installation.

**Comment by YKPDang** [comment]
>     3. I don't know where the ansible.cfg file is located on a docker installation.

For any new people stumbling upon this issue, it's in `/etc/ansible/ansible.cfg`
You can mount a volume to that directory but make sure to have https://github.com/semaphoreui/semaphore/blob/develop/deployment/docker/server/ansible.cfg on the host system already
