### ISSUE TITLE
Ansible Galaxy Collections in Semaphore

### ISSUE THREAD

**Issue by kleytonn** [ansible-semaphore/semaphore#682]
Hi,

I'm trying to use Ansible Galaxy Collections with Semaphore 2.7.0 but it only read requirements.yml for ansible roles. It is possible to download and install  Ansible Galaxy collections on Task Template running?

Thanks

**Comment by fiftin** [comment]
Hi @kleytonn,
Next command run before each Task Template running:
`ansible-galaxy install -r roles/requirements.yml --force`

You can put all you need to `roles/requirements.yml`, what the problem?

**Comment by nlvw** [comment]
@fiftin Collections are defined at `collections/requirements.yml`.  And the command for galaxy is `ansible-galaxy collection install -r collections/requirements.yml --force-with-deps`

You want to add `--force-with-deps` to both collections and role installs to ensure you grab and update dependencies.

**Comment by nlvw** [comment]
Looks like galaxy does support putting roles and collections in the same requirements.yml file.  I was unaware of that change so please ignore my first comment.

**Comment by ziouf** [comment]
Hello @fiftin, I think this issue can be re-open because I'm facing the same issue. 

# Exec env

```sh
# /usr/bin/semaphore version
v2.8.53

# ansible --version
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

# Context

I have a `collections/requirements.yml` file in my template git repository with the following content :
```yaml
---
collections:
- name: community.general
```

# Expected behaviour

At job startup, Semaphore checks that all requierments are installed and up to date for each 'collections/requierments.yml' and 'roles/requierments.yml' files before running playbook.

# Current behaviour

Only 'roles/requierments.yml' seem to be checked up at startup. And playbook fail with this error in my test scenario

```text
FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup('community.general.random_string', length=42) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup plugin (community.general.random_string) not found"}
``` 


Is there any mis-configuration on my side ?
Or, can you confirm that it's a missing feature ?

Thank you

**Comment by ziouf** [comment]
After a quick check in source code, it seems that semaphore ONLY check for role requierments, ignoring collections. 

https://github.com/ansible-semaphore/semaphore/blob/5f707bae4b0955b61784a86589162f7d9be59ebd/services/tasks/runner.go#L486-L512

We need to add the same feature for collections.

It is very concerning because collections are the new distribution standard for ansible content. 
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

**Comment by andreas-marschke** [comment]
@ziouf I have another MR in the same vein that would benefit code-review/help https://github.com/ansible-semaphore/semaphore/pull/1240
