### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by neilcavendish** [ansible-semaphore/semaphore#692]
Hey Guys,

New to ansible and semaphore. I have everything working except I have installed some collections, when running from the command line of ansible everything works. However when running in Semaphore it errors saying it cant find the collection. 

Listing playbook hosts failed: exit status 4 ERROR! couldn't resolve module/action 'ansible.posix.firewalld'. This often indicates a misspelling, missing collection, or incorrect module path. The error appears to be in '/etc/ansible/playbooks/repository_1/web.yaml': line 21, column 5, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: Configure Firewall ^ here

I have looked everywhere and am at a loss to why its not finding it. Can anyone please point me in the right direction. 

Thanks

**Comment by neilcavendish** [comment]
I also added the following into my requirements.yaml file and this still does not work. 

```
collections
  - ansible.posix
```

**Comment by ahmedsajid** [comment]
Do you see the collection under home directory?
```
$ ls -ltra ~/.ansible/collections/ansible_collections/ansible/
netcommon/ posix/     
```

Also is your Ansible host vs Semaphone host 2 different machines and what Ansible versions are being used on both machines?

**Comment by ahmedsajid** [comment]
Also not sure if this makes a difference but this is how I have the requirements.yml defined.
```
collections:
  - name: ansible.posix
  ```

**Comment by neilcavendish** [comment]
Yes the collection is there.

No they are running on the same machine. 

Ansible version is:

ansible 2.9.24
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, May 19 2021, 03:00:47) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]


I think ansible is installed as root but semaphore runs as user:ansible I permissioned the files so the owner is ansible but that did not change anything.

**Comment by neilcavendish** [comment]
I fixed it, I installed the collection to /usr/share/ansible/plugins/collections and that works

**Comment by ahmedsajid** [comment]
I was gonna suggest to check under Ansible user's home directory too. But installing under a global location would also work.

**Comment by fiftin** [comment]
@neilcavendish do you have this collection in `roles/requirements.yaml`?

**Comment by atika** [comment]
Semaphore define the `HOME` to the `config.TmpPath`, and when playbooks are run, ansible create the directory `.ansible` in this directory. It's the reason why user defined modules, collections, roles installed in the user home directory are not found.
By adding to the task the argument `["-vvv"]` you should see when the playbook are run the location of the config file and the directories where ansible search for modules.
```
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible/semaphore/playbooks/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
```
To test you can run `HOME=semaphore/playbooks ansible --version`

I created symlinks on this directory to my user collection, roles, etc. and it works.

The documentation should explain how to start with Semaphore, the different steps to configure it and how it works, because for me, and as a new ansible user, it's not obvious.
