### ISSUE TITLE
Environment variable to use postgresql

### ISSUE THREAD

**Issue by MrChausson** [ansible-semaphore/semaphore#729]
It is not possible to use a postgresql database by setting up an environment variable.  Or at least I don't know it. Which makes it unusable in docker.

Is there an env variable for this ?

**Comment by fiftin** [comment]
No, currenlty you can setup Postgres only in config file.

I agree it should be configurable via environment variables.

**Comment by mwxp06** [comment]
Very big workaround is run docker with mysql db and in created config switch db to Postgres...
But you need to have both db run, because semaphore is checking connection on starts - why? 
Why not after read data from config file?

**Comment by mwxp06** [comment]
@fiftin Please are you working on this issue in docker instance? 
Thank you so much

**Comment by fiftin** [comment]
@mwxp06 I'm not specialist in Docker, I need help :-)

**Comment by mwxp06** [comment]
@fiftin If I am not wrong, there is a little bit changes:
File: docker-compose.yml - add new variable to environment, because you are using for mysql 1, so default is one
`environment: 
      SEMAPHORE_DB_DIALECT_ID: 1
`

File: semaphore-wrapper - change mysqladmin ping and add new variable
(renamed to txt to possibility upload here)
[semaphore-wrapper.txt](https://github.com/ansible-semaphore/semaphore/files/7344948/semaphore-wrapper.txt)

**Comment by mwxp06** [comment]
@fiftin Created pull request:
https://github.com/ansible-semaphore/semaphore/pull/773

Please merge

**Comment by ryan-morris** [comment]
Just to confirm, `SEMAPHORE_DB_DIALECT: postgres` now works when set in docker-compose for me with latest version. Thanks!
